import javax.swing.*;
import java.awt.*;
/*
                    ***WARNING***
This code was Generated By Chat GPT as a way to demonstrate 
how to implement a timetables that uses a pop up window. It
is meant for educational purposes, submit at your own risk.
Sources to understand javax.siwing library: https://www.geeksforgeeks.org/java/introduction-to-java-swing/
java.awt library(Responsible for GUI): https://www.geeksforgeeks.org/java/java-awt-tutorial/
*/
public class Main {

    private static final String[] DAYS = {"Mon", "Tue", "Wed", "Thu", "Fri"};
    private static final String[] TIMES = {
            "8 AM", "9 AM", "10 AM", "11 AM",
            "12 PM", "1 PM", "2 PM", "3 PM", "4 PM"
    };

    // Default: user is free for all slots
    private boolean[][] isFree = new boolean[DAYS.length][TIMES.length];

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new Main().showMenu());
    }

    // Show starting menu
    public void showMenu() {

        // Initialize default true for the whole timetable
        for (int d = 0; d < DAYS.length; d++) {
            for (int t = 0; t < TIMES.length; t++) {
                isFree[d][t] = true;
            }
        }

        String[] options = {"Edit Schedule", "Exit"};
        int choice = JOptionPane.showOptionDialog(
                null,
                "Would you like to view or change your schedule?",
                "Schedule Menu",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]
        );

        if (choice == 0) {
            createWindow();
        } else {
            System.exit(0);
        }
    }

    // Create timetable popup
    public void createWindow() {
        JFrame frame = new JFrame("Editable Weekly Timetable");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(900, 500);

        JPanel mainPanel = new JPanel(new BorderLayout());
        JPanel gridPanel = new JPanel(new GridLayout(TIMES.length + 1, DAYS.length + 1));

        // Top-left empty cell
        gridPanel.add(new JLabel(""));

        // Day headers
        for (String day : DAYS) {
            JLabel header = new JLabel(day, SwingConstants.CENTER);
            header.setFont(new Font("Arial", Font.BOLD, 16));
            gridPanel.add(header);
        }

        // Build timetable
        for (int t = 0; t < TIMES.length; t++) {

            JLabel timeLabel = new JLabel(TIMES[t], SwingConstants.CENTER);
            timeLabel.setFont(new Font("Arial", Font.BOLD, 14));
            gridPanel.add(timeLabel);

            for (int d = 0; d < DAYS.length; d++) {

                JButton slot = new JButton();
                slot.setOpaque(true);

                // Set initial default color (true = Free)
                updateButtonColor(slot, isFree[d][t]);

                int dayIndex = d;
                int timeIndex = t;

                // Toggle availability
                slot.addActionListener(e -> {
                    isFree[dayIndex][timeIndex] = !isFree[dayIndex][timeIndex];
                    updateButtonColor(slot, isFree[dayIndex][timeIndex]);
                });

                gridPanel.add(slot);
            }
        }

        // Bottom buttons (Back to Menu / Exit)
        JPanel bottomPanel = new JPanel();
        JButton backButton = new JButton("Back to Menu");
        JButton exitButton = new JButton("Exit Program");

        backButton.addActionListener(e -> {
            frame.dispose();
            showMenu();
        });

        exitButton.addActionListener(e -> System.exit(0));

        bottomPanel.add(backButton);
        bottomPanel.add(exitButton);

        mainPanel.add(gridPanel, BorderLayout.CENTER);
        mainPanel.add(bottomPanel, BorderLayout.SOUTH);

        frame.add(mainPanel);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    // Update button to reflect true/false state
    private void updateButtonColor(JButton btn, boolean free) {
        if (free) {
            btn.setBackground(Color.GREEN);
            btn.setText("Free");
        } else {
            btn.setBackground(Color.RED);
            btn.setText("Busy");
        }
    }
}
